"use client"

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ChakraProvider, cookieStorageManagerSSR, localStorageManager } from "@chakra-ui/react";
import { useState, useEffect } from "react";
import { RecoilRoot } from "recoil";
import { SocketContextProvider } from "../context/socket/SocketContext";


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [colorModeManager, setColorModeManager] = useState(localStorageManager);

  useEffect(() => {
    // Check if we are on the server
    if (typeof document === "undefined") {
      setColorModeManager(cookieStorageManagerSSR(""));
    }
  }, []);


  return (
    <html lang="en">
      <body>
        <ChakraProvider colorModeManager={colorModeManager}>
          <RecoilRoot>
            <SocketContextProvider>
              {children}
            </SocketContextProvider>
          </RecoilRoot>
        </ChakraProvider>
      </body>
    </html>
  );
}